baseURL: /neverpile-eureka-documentation/
title: Neverpile eureka

enableRobotsTXT: true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme: 
  - docsy

# Will give values to .Lastmod etc.
enableGitInfo: true

# Language settings
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

# Useful when translating.
enableMissingTranslationPlaceholders: true

disableKinds: 
  - taxonomy
  - taxonomyTerm

# Highlighting config
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false

#pygmentsOptions: linenos=table
# See https://help.farbox.com/pygments.html
pygmentsStyle: tango

# Configure how URLs look like per section.
permalinks:
  blog: /:section/:year/:month/:day/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true

# Image processing configuration.
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

services:
  googleAnalytics:
    # Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
    # id: UA-00000000-0
  
# Language configuration
languages:
  en:
    title: neverpile eureka - documentation
    description: neverpile eureka - the archive system for the cloud generation
    languageName: English
    # Weight used for sorting.
    weight: 1
    
    #  de:
    #    title: neverpile eureka - Dokumentation
    #    description: neverpile eureka - das revisionssichere Archivsystem für die Cloud-Generation
    #    languageName: Deutsch
    #    contentDir: content/no
    #    time_format_default: 02.01.2006
    #    time_format_blog: 02.01.2006


# Everything below this are Site Params

params:
  copyright: levigo holding GmbH
  privacy_policy: https://www.levigo.de/datenschutz/
  
  # First one is picked as the Twitter card image if not set on page.
  # images: [images/project-illustration.png]
  
  # Menu title if your navbar has a versions selector to access old versions of your site.
  # This menu appears only if you have at least one [params.versions] set.
  version_menu: Releases
  
  # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
  github_repo: https://github.com/levigo/neverpile-eureka-documentation
  
  # An optional link to a related project repo. For example, the sibling repository where your product code lives.
  github_project_repo: https://github.com/levigo/neverpile-eureka
  
  # Specify a value here if your content directory is not in your repo's root directory
  # github_subdir: 
  
  # Google Custom Search Engine ID. Remove or comment out to disable search.
  # gcs_engine_id: 011737558837375720776:fsdu1nryfng
  
  # Enable Algolia DocSearch
  algolia_docsearch: false
  
  # Enable Lunr.js offline search
  offlineSearch: true

  # User interface configuration
  ui:
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: false
    
    #  Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    
    #  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: false
    
    #  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    navbar_logo: true
    
    # Set to true to disable the About link in the site footer
    footer_about_disable: true

  # Adds a H2 section titled Feedback to the bottom of each doc. The responses are sent to Google Analytics as events.
  # This feature depends on [services.googleAnalytics] and will be disabled if services.googleAnalytics.id is not set.
  # If you want this feature, but occasionally need to remove the Feedback section from a single page,
  # add hide_feedback: true to the page's front matter.
  feedback:
    enable: true
    # The responses that the user sees after clicking yes (the page was helpful) or no (the page was not helpful).
    yes: 'Glad to hear it! Please <a href=https://github.com/USERNAME/REPOSITORY/issues/new>tell us how we can improve</a>.'
    no: 'Sorry to hear that. Please <a href=https://github.com/USERNAME/REPOSITORY/issues/new>tell us how we can improve</a>.'

  links:
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    user:
#      - name: User mailing list
#        url: https://example.org/mail
#        icon: fa fa-envelope
#        desc: Discussion and help from your fellow users
#
#      - name: Twitter
#        url: https://example.org/twitter
#        icon: fab fa-twitter
#        desc: Follow us on Twitter to get the latest news!
#
#      - name: Stack Overflow
#        url: https://example.org/stack
#        icon: fab fa-stack-overflow
#        desc: Practical questions and curated answers

    developer:
      # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
      - name: GitHub
        url: https://github.com/levigo/neverpile-eureka
        icon: fab fa-github
        desc: Development takes place here!

#      - name: Slack
#        url: https://example.org/slack
#        icon: fab fa-slack
#        desc: Chat with other project developers
#
#      - name: Developer mailing list
#        url: https://example.org/mail
#        icon: fa fa-envelope
#        desc: Discuss development issues around the project
