name: Continuous Delivery (automatic documentation build and deployment)

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive 
    
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x 
    - name: npm install
      run: npm install --prefix website\
      
    - name: Build
      run: npm run build --prefix website\

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./website/build/neverpile-eureka-documentation  

    ## Notify Slack
    - name: Notify slack
      uses: hennejg/slack-build-notifier@v1.1
      with:
        username: GitHub
        icon_emoji: octocat
        text: Deployed new documentation from *${{ github.repository }}* to https://levigo.github.io/neverpile-eureka-documentation/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}