name: Continuous Delivery (automatic documentation build and deployment)

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive 
    
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        hugo-version: 0.60.1
        extended: true
    
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x 
    - name: npm install
      run: npm install
      
    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public  

    ## Notify Slack
    - name: Notify slack
      uses: hennejg/slack-build-notifier@v1.1
      with:
        username: GitHub
        icon_emoji: octocat
        text: Deployed new documentation from *${{ github.repository }}* to https://levigo.github.io/neverpile-eureka-documentation/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}